# Setup
debug: False
logdir: "logs/"
seed: 0
device: "cuda:0" # cuda:0 / cpu

# Env
size: [128, 128]
grayscale: True

# Training
toy_env: False
n_episodes: 5000
max_episode_steps: 100
env_id: "donkey-minimonaco-track-v0" # "donkey-generated-roads-v0"
max_grad_norm: 100

# Model
batch_size: 8
H: 512 # discrete h state
num_categoricals: 32
num_classes: 32

# MLP
mlp_n_layers: 3
mlp_hidden_dims: 256

# Actor-Critic
action_clip: 1 # action range: [-action_clip, action_clip]