# Setup
debug: False
logdir: "logs/"
seed: 0
device: "cuda:0" # cuda:0 / cpu

# Env
size: [128, 128]
grayscale: True

# Training
toy_env: True
n_episodes: 5000
max_episode_steps: 500
max_imagination_episode_steps: 200
imagination_timesteps_per_model_update: 500
env_id: "donkey-minimonaco-track-v0" # "donkey-generated-roads-v0"
max_grad_norm: 1

# Model
batch_size: 1
H: 512 # discrete h state
num_categoricals: 32
num_classes: 32
buffer_size: 10000

# MLP
mlp_n_layers: 3
mlp_hidden_dims: 256

# RL Agent
verbose: 0
imagination_progress_bar: False
action_clip: 1 # action range: [-action_clip, action_clip]
