name: push

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update pip
        run: python -m pip install --upgrade pip; python -m pip install --upgrade setuptools==65.5.0 # version needed for gym

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run preprocessing tests
        run: python tests/test_preprocessing.py

      - name: Run two-hot encoding tests
        run: python tests/test_two_hot_encoding.py

      - name: Run DiscreteActorCritic tests
        run: python tests/test_discrete_actor_critic.py

      - name: Run CategoricalStraightThrough tests
        run: python tests/test_categorical_straight_through.py
      
      - name: Run CategoricalVAE tests
        run: python tests/test_categorical_vae.py

      - name: Run RSSM tests
        run: python tests/test_rssm.py
