name: unit-tests

on: [push, pull_request]

jobs:
  test-all:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update pip
        run: pip install --upgrade pip; pip install setuptools==66

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python tests/test_src.py

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-